"""Pipeline configuration — reads from environment or uses defaults."""

import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

BASE_DIR = Path(__file__).parent.parent
# Pipeline settings use a neutral PW_ (pathway) env prefix — this tool is generic
# (any signaling pathway), so nothing here is tied to a specific pathway.
OUTPUT_DIR = Path(os.getenv("PW_OUTPUT_DIR", str(BASE_DIR / "results")))
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# Which installed LLM CLI drives the reasoning calls. Detected options typically
# include: agy, claude, gemini, codex, ollama. Override with --cli or PW_LLM_CLI.
LLM_CLI = os.getenv("PW_LLM_CLI", "agy")
LLM_TIMEOUT = int(os.getenv("PW_LLM_TIMEOUT", "120"))       # seconds per call
OLLAMA_MODEL = os.getenv("PW_OLLAMA_MODEL", "llama3.1")     # used only if LLM_CLI=ollama

MAX_REFLECTION_ITERATIONS = int(os.getenv("PW_MAX_REFLECTIONS", "2"))

# --- Pathway relevance filtering -------------------------------------------
# Two data-driven stages remove hub-gene over-inclusion WITHOUT any hardcoded
# pathway names or ID patterns:
#   1. Hypergeometric over-representation (ORA) of the seed-gene set.
#   2. LLM relevance gate driven by the user query.
ENRICHMENT_ENABLED = os.getenv("PW_ENRICHMENT", "1") != "0"
# Background gene universe for the hypergeometric test (protein-coding genome).
ENRICHMENT_BACKGROUND_SIZE = int(os.getenv("PW_ENRICHMENT_BACKGROUND", "20000"))
# BH-adjusted p-value cutoff; a pathway must be enriched for the seed set to pass.
ENRICHMENT_FDR = float(os.getenv("PW_ENRICHMENT_FDR", "0.05"))
# Minimum raw overlap with the seed set (guards tiny-pathway false positives).
ENRICHMENT_MIN_OVERLAP = int(os.getenv("PW_ENRICHMENT_MIN_OVERLAP", "2"))
# LLM relevance gate on the survivors of stage 1.
LLM_RELEVANCE_GATE = os.getenv("PW_LLM_GATE", "1") != "0"
LLM_GATE_CHUNK = int(os.getenv("PW_LLM_GATE_CHUNK", "40"))

# Databases queried (extend here to add more)
ENABLED_DATABASES = ["KEGG", "Reactome", "SIGNOR"]

# No hardcoded pathway defaults — all search terms and seed genes are
# generated by the planner LLM from the user query at runtime.

# API endpoints
KEGG_BASE = "https://rest.kegg.jp"
REACTOME_BASE = "https://reactome.org/ContentService"
SIGNOR_BASE = "https://signor.uniroma2.it"
MYGENE_BASE = "https://mygene.info/v3"
